facebook:
  client:
    clientId: 121972615808740
    clientSecret: 7b325fbd98b3dd056a3d755a421833f2
    accessTokenUri: https://graph.facebook.com/oauth/access_token
    userAuthorizationUri: https://www.facebook.com/dialog/oauth?display=popup
    tokenName: oauth_token
    authenticationSchema: query
    clientAuthenticationSchema: form
    scope: email
  resource:
    userInfoUri: https://graph.facebook.com/me?fields=id,name,email,link

google:
  client:
    clientId: 181353459396-53apkijgalmqqp1md8atbc9hu13vnlg9.apps.googleusercontent.com
    clientSecret: n45P_WaF9VrcUlI6GcL5auvv
    accessTokenUri: https://accounts.google.com/o/oauth2/token
    userAuthorizationUri: https://accounts.google.com/o/oauth2/auth
    scope: email, profile
  resource:
    userInfoUri: https://www.googleapis.com/oauth2/v2/userinfo

kakao:
  client:
    clientId: e0c50e5a2cb8f57bb4ce6d40b7e8a442
    clientSecret: IHIpS1CVMV94nQBtjvB1esGOnS2eDtSp
    accessTokenUri: https://kauth.kakao.com/oauth/token
    userAuthorizationUri: https://kauth.kakao.com/oauth/authorize
  resource:
    userInfoUri: https://kapi.kakao.com/v1/user/me